### ISSUE TITLE
Feat/class/CRUD

### ISSUE THREAD

**Issue by Okafor-Ifeanyi** [Okafor-Ifeanyi/csc_school_portal#16]
### Request Description

CRUD - Create, Read, Update, Delete, Login
This endpoint should consist of the endpoints to perform all these functions for the class
This issue sets the base for the class model in which other function will be developed on.

### Use Case

As an Admin, I should have the endpoint to Create, Read, Update or Delete  a Class

**Comment by andrysatko** [comment]
@Okafor-Ifeanyi , are you considering any contribution to your project?

**Comment by Okafor-Ifeanyi** [comment]
@andrysatko sure send me an email on ifeanyi.okafor.bio@gmail.com here, let's collaborate
